### ISSUE TITLE
`Show the Welcome Guide` option button emits 2 clicks sound 

### ISSUE THREAD

**Issue by thanhgaming5550** [tetrio/issues#1003]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 18362.30

### Browser and version

Chrome 103.0.5060.53

### Describe the bug/issue

`Show the Welcome Guide` button in `Config` (Video & Interface section) when changing options will sound the sound of 2 clicks

### Reproducing

1. Open TETR.IO (Broswer or Desktop Client) and login
2. Go to `Config` -> `Video & Interface`
3. Click `Show the Welcome Guide` option button

### Expected behavior

Emits 2 sounds instead of 1

### Screenshots

https://user-images.githubusercontent.com/62001770/185797656-a95486c1-daf1-4ab1-915f-5647172e29c1.mp4

**Comment by ZaptorZap** [comment]
I can replicate it here, but with the way it behaves on my computer, I could see why nobody's found this yet. Instead of sequentially playing one-by-one, they play simultaneously, creating a click double the volume. A desynchronization is noticable on the desktop client:

https://user-images.githubusercontent.com/64891705/185866944-4a27c50a-9655-49ae-ad18-32fcca1a7b29.mp4

**Comment by thanhgaming5550** [comment]
@ZaptorZap The `Got It!` Button too

https://user-images.githubusercontent.com/62001770/186399742-5f2899c3-b741-4eca-b866-748bb839b44b.mp4

**Comment by Dimentio** [comment]
That was an interesting issue report, fixed in upcoming update!
