### ISSUE TITLE
Kick = Ban in Multiplayer Room

### ISSUE THREAD

**Issue by thanhgaming5550** [tetrio/issues#1012]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 18362.30

### Browser and version

Chrome 103.0.5060.53

### Describe the bug/issue

When you kick or ban (both cases) a player from the Room, that player will be **BANNED** from this room, automatically **Disconnected the Current Server**, showing **KICKED message** and will have to **Restart TETR.IO** to join another room or play something.

### Reproducing

1. Kick/Ban someone in your Multiplayer Room
2. See the Result at their Client

### Expected behavior

Players who are kicked will be notified that they have been kicked, do not have to restart TETR.IO and can rejoin that room as well as other rooms (that are not prohibited).

Players who are banned will be notified that they have been kicked (or banned), do not have to restart TETR.IO and cannot rejoin that room (can join other rooms that are not prohibited).

### Screenshots

https://streamable.com/4np6b9

**Comment by ZaptorZap** [comment]
Sorry, but this is very clearly intended by osk as a feature of the banning feature. You may read the related patchnotes [here](https://tetr.io/about/patchnotes/#chlog_6_1_3).
> ➔ Kicking someone from a room automatically bans them for 15 minutes.

As for rationale behind the decision: it's similar to when you report another user. That user is immediately blocked as well, and this simple extra measure has **instantly resolved** many incidents over direct message harassment(although of course the offending user receives further punishments once we may review the report). The same may be true over offensive messages in a public room, much like the feature regarding #1013 aims to solve.

Furthermore, we understand that the kick may have been issued for less serious reasons, such as evening out the player list by kicking a professional player who'd otherwise win every match. We understand that a "ban" for such an occasion implies **harsh results**, so we keep a more moderate response to keep those players in check—otherwise, many members would immediately disregard the kick and rejoin, wasting everyone's time.

```bash
# If you suspect a member of evading per-room bans with "anonymous" accounts, please **report** them. 
# Evasion of per-room bans is against the rules, and evading users may see their main account restricted.
```

At the end of the day, a kick from a room host implies a clear message to our reasoning: the kicked player is **unwelcome** in the room, and shouldn't be allowed to **immediately** rejoin. Afterall, why legitimately kick someone, only to _hope_ they immediately rejoin? As for illegitimate kicks, such as "inside jokes" played on trusted friends, well, it's very possible to use the `/unban` command to unban the individual in question. In fact, your trusted friend was informed to ask directly with the below message:
![image](https://user-images.githubusercontent.com/64891705/187850003-924890e3-ec83-4350-9cd0-df3160209540.png)
