### ISSUE TITLE
Remove passthrough (in tetra league)

### ISSUE THREAD

**Issue by Imagine-Gamer** [tetrio/issues#1034]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Passthrough is easily one of the most annoying things that any player can experience in tetra league. It occurs when both players send lines at the same time. It's unnecessary, and frustrating to deal with. No other Tetris game really has this "passthrough" issue except tetrio.

### Describe the solution you'd like

The solution is simple:
When both send lines at the same time, it should cancel each other out, not send lines both at them at the same time. Example, if both players send a t spin double at the same time, it should cancel the garbage for both players and should have no garbage being sent to anyone.

### Describe alternatives you've considered

I'm not sure if there's any other alternative that can fully cover the passthrough issue.

### Additional context

https://www.twitch.tv/teamtsd/clip/CloudySoftFerretSuperVinlin-UjAA5uyO-k0s4TV6?filter=clips&range=all&sort=time
passthrough example

**Comment by ZaptorZap** [comment]
Sorry, but passthrough was **[very much so already removed](https://tetris.wiki/TETR.IO#Professional_Concerns:_The_Removal_of_Passthrough)**. What you're experiencing here is a byproduct of natural networking delays, which is outside the scope of this repository. That said, the effect networking delays has on this issue is well known and [documented in the patchnotes](https://tetr.io/about/patchnotes/#chlog_6_1_0)—as of now the only fix **would impact user input during live games**, such as how similar stacker game Puyo Puyo Tetris handles lag. (And believe me, the community has some stern opinions about that sort of handling, even with the intensive restrictions on handling PPT imposes.)
