### ISSUE TITLE
Nationality issues

### ISSUE THREAD

**Issue by fiuhgrhr** [tetrio/issues#1060]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

My nationality is listed as British, however I am Scottish. I would want my country to be recognised rather than being all lumped in together. I wouldn't even mind if there was a shared leaderboard maintained between all countries if that would simplify things, but having my country displayed accurately shouldn't need to be requested for to begin with. 

### Describe the solution you'd like

Have Scotland, Wales, NI and England be recognised separately, with their flags under this part of a user's profile.

(and just to clarify, having britain as the main place and one of the four as a sub heading wouldn't cut it either)

### Describe alternatives you've considered

N/A - as there isn't really an effective alternative.

**Comment by ZaptorZap** [comment]
Well, those nationalities certainly exist and do have their own leaderboards within [the TETRA CHANNEL](https://ch.tetr.io/players#GB-SCT), but you need Supporter to actually change your flag to them. I think there's an issue in how the information we get off your network, said information being from [Cloudflare](https://www.cloudflare.com/), **doesn't** specify yourself as in Scotland—it's an issue with the source itself. Not sure how tenable this issue is for us as we don't run geolocation services...

**Comment by fiuhgrhr** [comment]
Hmm maybe a suggestion could be that when an account is created, if the UK is detected as your location there could be an option to select which is accurate?

**Comment by iDm1** [comment]
Nationality should be selected during registration process and there should be clear that further changes are under a paywall.

**Comment by o5k** [comment]
we use Cloudflare's reported country to select your initial country. if it's incorrect you should ask them; it's something that can happen if your IP was juggled around between providers.. my own IP often shows up as German for that reason
if you got the wrong country due to this, you can contact our support personally
