### ISSUE TITLE
Ability to tab in and tab out.

### ISSUE THREAD

**Issue by QWSMI** [tetrio/issues#1091]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 11 and chrome OS

### Browser and version

Chrome 111.0.5563.54

### Describe the bug/issue

When you tab out on TETR.IO you freeze and when you play TETR league it becomes REALLY annoying to compete when they do that. 

### Reproducing

1 when you are about to die in tetr league
2 open new tab or click on tab 
3 boom your frozen

### Expected behavior

Make it so when you tab out you disconnect.

### Screenshots

N/A

### Console logs

N/A

### Additional context

N/A

**Comment by ZaptorZap** [comment]
Sorry, but this is infeasible. To start off, I'm not seeing super promising results when trying to figure out if it's definitively possible to tell whether or not a user has tabbed off the page, so making the game generally **worse** at retaining ongoing connections is something remotely nobody wants implemented. Furthermore, I fail to see the competitive benefit of maliciously using this browser quirk to gain an advantage. Afterall, the concept of a conventional lagswitch is that **you are still controlling the game while it is enabled**. If you're not on the tab, you cannot control the board.

Of course, if you're tabbed out for long enough you **will** disconnect simply because the browser will not allow TETR.IO to send an appropriate amount of ping packets anymore.
