### ISSUE TITLE
bug in Tetr.io account deletion

### ISSUE THREAD

**Issue by TASZITE** [tetrio/issues#1127]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Android

### Browser and version

FirefoxNightfly 

### Describe the bug/issue

I have 2 accounts one is logged in Firefox And the other in Samsung Internet I want to delete my account that is logged in Samsung Internet the id is: THEYLLER (this account I stopped playing a year ago) I had created another one called TASZITE (I'm playing with it more.) When I try to delete it it stays there. Unfortunately I don't have a demo video. account id I want to delete: THEYLLER

### Reproducing

Nenhum

### Expected behavior

My account is deleted

### Screenshots

Nenhum

### Console logs

Nenhum

### Additional context

Nenhum

**Comment by ZaptorZap** [comment]
Sorry, but this repository isn't for account support. For that, please visit https://tetr.io/about/support as you were instructed to right now in the TETR.IO Discord server. Since cases such as these involve sensitive details, I'll be locking the thread now. Furthermore, since _Samsung Internet_ isn't officially supported, this issue is invalid to begin with.
