### ISSUE TITLE
You can start a custom game with invalid option values

### ISSUE THREAD

**Issue by Wirtualnosc** [tetrio/issues#113]
### Description
You can start a custom game with invalid option values. Some values will pass correctly, others will do completely unintended effects, even others will completely hang the game.

### Reproduction
Start a custom game:
- To see an invalid option that actually works normally, set Countdown Count to 100.
- To see an invalid option that works normally but definitely wouldn't be intended, set Lines objective to 1.5.
- To see an option that does unintended effects, set Countdown Interval to 1.5. Game will behave as if that option was set to 0 (which is another invalid value).
- To see a game hang, set Countdown Count to "1e20".

### Expected behavior
If there's any invalid field set, you either shouldn't be able to start a game (preferred) or invalid fields should use default values instead.

### Setup
Firefox 73.0.1 Linux

### Additional context
When terminating the browser hang (not that it matters I guess?):
```
Error: Script terminated by timeout at:
startGame/<@https://tetr.io:4477/js/tetrio.js:23:286585
e@https://tetr.io:4477/js/tetrio.js:23:46594
startGame@https://tetr.io:4477/js/tetrio.js:23:285899
p@https://tetr.io:4477/js/tetrio.js:23:146621
@https://tetr.io:4477/js/tetrio.js:23:120926
```

**Comment by Wirtualnosc** [comment]
I should also mention that ideally you should restrict values inside input boxes too
`<input type="number">` might save some work but browser support on what you're allowed to type inside might be uh, fuzzy

**Comment by csq-curiosity** [comment]
Here's a list of custom game variables that may be adversely affected. The ones marked bold is likely game-breaking:

Game tab:

Stock: Should be a nonnegative integer. Currently, any non-integer numbers are processed with a ceiling function; that is, any number that is not an integer is rounded up to the nearest integer. Except for negative numbers, which are all considered as zero.

Next pieces: Should be a nonnegative integer. Currently, any non-integer numbers between 1 and 5 are processed with a floor function; that is, any decimal points are dropped. Any number below 1 is considered as 1, and any number above 5 is considered as 5.

ARE and Line clear delay: If any negative integer is entered, the game treats it like 0. **If any non-integer number is entered, the delay is either ridiculously long or indefinite, effectively softlocking the game.** (Retry and forfeit is still possible)

Level increase: Given that you don't play with static levelling, **setting into a negative number instantly completely freezes the game.**

Starting level: Not only the decimals are allowed, negative numbers are. Playing with these settings work as "intended", in that your score will start to fall in the decimal and negative range. ~~Please don't fix this I love it~~

Level static speed: Setting into a decimal calculates it like normal-ish. If you set it to 0.1, every line will give you 10 levels. This is fine for the most part, unless you set it to 0.0000001 and have the game level up by 40 million, which... um...
https://discord.com/channels/673303546107658242/674421736162197515/714300331022090260

Base gravity and Gravity increase: Now this one is a little weird. They seem to be variables from the common gravity formula:
Time = (0.8-((Level-1)*0.007))^(Level-1) (where base gravity defaults to 0.8 and gravity increase defaults to 0.007.)
Technically, there is nothing stopping you from entering values of base gravity or gravity increase to be negative, which was a strange quirk I found by fitting nes gravity data to that formula:
https://discord.com/channels/673303546107658242/674421736162197515/725965877060829235
This works well... until around Lv40, and the gravity starts to slow down. (Credit to ZaptorZap for finding this quirk)
https://discord.com/channels/673303546107658242/674421736162197515/726003186695012403
Now, there is technically nothing wrong with this, but you would expect the gravity to be strictly increasing in order for it to function normally. Even more strangely, the master levels affect the lock delay, but they still rely on the gravity formula. So when you play with the settings above the lock delay does go nuts, but since the gravity starts to decrease, the game eventually gets easier... as you level up.
I don't know if this is something you can fix, or whether you should fix it in the first place. Just a little heads up I guess.

Lock delay: Decimals are processed as is, probably. Negative integers are processed as 0.

Objectives tab:

Lines: Setting it into a decimal will process it as is; If you exceed that number, the game will end. Setting it into either zero or a negative number will instantly end the custom game as it begins, provided that the objective is lines.

Timer: Setting it into a decimal will process it as is. Setting it into either zero or a negative number will instantly end the custom game as it begins, provided that the objective is timed.

Meta tab:

Countdown count: Setting it into a decimal will process it as is. If you set it to 1.5, it will count, 1.5, 0.5 and GO!, but the last 0.5 will take half a second. Setting it into 0 will default to 3. Setting it into a negative number will start to bleed into the "time before countdown" time and "time before start" time. Sufficiently small negative numbers will cause the game to start the moment you press start button.

Countdown interval: Setting it into a decimal will process it as is. Setting it into a negative number will cause it to count in reverse order; GO!, 1, 2, 3 and so on; except it will attempt to process that within the designated "time before countdown" time.
If Countdown count and Countdown interval variables don't fit into the Time before countdown variable, the game will attempt to load all the "residual" countdown at once causing a massive lag. For example, if you have Countdown count as 300 and interval as -1000, but your time before countdown is 3000, the game will attempt to load every countdown text from GO! to 298 at the first second, then 299 on the second second, and 300 in the third second. This can be potentially game breaking if you have huge numbers of countdown.

Time before countdown: Setting it into a decimal will process it as is. Setting it into a negative number will start to bleed into the countdown. If your Time before countdown is -1000, with the countdown count of 3 and interval of 1000, the game will load the text 3 and 2 at the same time.

Time before start: Setting it into a decimal will process it as is. Setting it into a negative number will start to bleed into the countdown. If your Time before start is -1000, with the countdown count of 3 and interval of 1000, the game will load the text 3 and 2 at the same time.

**Comment by csq-curiosity** [comment]
Obligatory update comment. Additional discovery noted below:

Game tab:

> Starting level: Not only the decimals are allowed, negative numbers are. Playing with these settings work as "intended", in that your score will start to fall in the decimal and negative range.

Something I noticed on the first experiment run but didn't clarify is that the soft drop/hard drop scores are not reflected on the score multiplier. Just a point of note; I am unsure if the level multiplier should affect drop bonuses.

> Lock delay: Decimals are processed as is, probably. Negative integers are processed as 0.

New discovery: While setting the lock delay to a negative number is likely processed as 0, actually setting the lock delay to 0 causes the game to consider the lock delay as the default value (which is 30). A strange discrepancy, considering that both decimal and negative lock delay are processed without causing any issue.

Meta tab:

> Countdown count / Countdown interval / Time before countdown / Time before start

New discovery: All of these variables with the exception of "Time before start" are overridden when you enable stride mode. This causes the side effects of the first 3 variables to be negated, but adverse effects arising from setting time before start as a negative number still causes the same issue.

It should also be noted that the side effects of negative time before start and/or negative time before countdown is limited to starting the first game. Restarting the game by pressing the restart key is not adversely affected by these settings.

**Comment by csq-curiosity** [comment]
bumpy
