### ISSUE TITLE
Save entries for more than 10 Tetra League records

### ISSUE THREAD

**Issue by SpartanApple** [tetrio/issues#1242]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I am interested in `https://ch.tetr.io/api/streams/league_userrecent_<player_id>` API having pagination to allow for more than 10 previous game results. 

### Describe the solution you'd like

Currently a call to `https://ch.tetr.io/api/streams/league_userrecent_<player_id>` only provides information on the last 10 games played for a user. I am interested in having additional game history shown via pagination. 

### Describe alternatives you've considered

Alternatively/additionally, allow for more than 10 results to be requested in a page.

### Additional context

I would like to make a page that allows players to view a chart of their rankings overtime as well as other game results. It would be very useful to have more than a last-10 game context window. Thank you!

**Comment by ZaptorZap** [comment]
Well the implication of having pages extends far beyond just adding a new query to the Tetra Channel API endpoint. The entries beyond the 10th are immediately deleted to save on server space, which can be an issue at this game's size.

For a long time, the proposed application you intend to develop has been a main game feature request at #830, but the data would probably stay as the simplified PPS • APM • VS—no replays beyond the 10th game. A large reason #830 is in limbo is because of TETR.IO's alpha state: osk intends to launch these graphs and more alongside a full Tetra League wipe. If he released it now, people's "peaks" wouldn't *really* be their peaks, because the dataset is inherently incomplete. Using https://archive.org/details/tetrio-stats doesn't change this—it has an imperfect data resolution.

I'll be renaming this request because if this were released, it should absolutely not be limited to API endpoints. Players should be allowed to go page by page at their own leisure at https://ch.tetr.io/.

**Comment by AzuraHorizons** [comment]
Should this be closed as completed?

**Comment by ZaptorZap** [comment]
ya
