### ISSUE TITLE
incorrect player statistics. 

### ISSUE THREAD

**Issue by Maylit336** [tetrio/issues#1245]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Android (doesnt matter)

### Browser and version

Chrome 120.0.6099.145 (doesnt matter)

### Describe the bug/issue

im SpectoCube336, usually now my Pps is 1.35 or bigger, Apm is 30 or bigger. vs is 60 or bigger.
but when i look in my statistics, There is 1 pps, 20 apm, 30 vs. usually i dont play Tetrio league, because i dont want to lose, so i usually practive in list rooms. but for my statistics to be correct, I need to play several matches in tetrio league for everything to be appropriate. however, I go there when I am sure that my skill has higher than earlier.
### Reproducing

1.Search in Tetrio channel "SpectoCube336"
2. Look at tetrio league statistics
3. see my stats

### Expected behavior

I expected that statistics from custom rooms, zen, 40 lines, blitz would also be taken into account, but the Game only counts statistics in tetrio league. 
I would like the player profile to also include pps, apm, vs 40 lines, blitz, zen, and Just Custom rooms information. 
The best thing to do is to make the game count stat information when I play list rooms. 

### Screenshots

![Screenshot_20240105_181216_Chrome](https://github.com/tetrio/issues/assets/153793513/87ce80cf-d8a7-4a78-b01e-14b9ef90f3cb)
![Screenshot_20240105_181338_Chrome](https://github.com/tetrio/issues/assets/153793513/07432025-794b-42b3-9a83-497ff69aa1b7)

### Console logs

(i cant, im on phone.)

### Additional context

![sf-94971bcb-c9bd-49a6-81ec-ede539f0c9e1](https://github.com/tetrio/issues/assets/153793513/b07b5881-757d-411c-9fdc-3cedf68623c1)
(little off topic, but still about stats) i seen sats in tetrio championship in the form of a picture (presentation). it would be cool if the same was in tetrio channel
(picture was taken from Discord bot)

**Comment by ZaptorZap** [comment]
This is intended as the other proposed modes often don't even measure APM in any relevant manner(afterall, VS involves _Garbage Cleared_, and in 40L/Blitz, there is no garbage to clear), and when they do, such as in the case of Custom Rooms, it's very possible that a room host will bump up the garbage multiplier by a hundred or so and cause ridiculous stats to appear on profiles. 

This is the **studied case** with [Jstris](https://jstris.jezevec10.com/) user profiles. For example, [jez's profile](https://jstris.jezevec10.com/u/jez) indicates that he is capable of doing a maximum **907.22 APM** over one match. This statistic is dubious and unhelpful.

It should be clear that the statistic is Tetra League exclusive, due to the very purposeful boundaries separating these statistics from all other statistics on your profile, card or standalone userpage. Tetra League's environment is extremely controlled and consistent to what players expect. Even if custom room stats were counted _only if_ the default settings were enabled, it would still impact average statistics in an unintended way.
