### ISSUE TITLE
Achievement system

### ISSUE THREAD

**Issue by mat1jaczyyy** [tetrio/issues#23]
An achievement system would allow newcomers to work towards goals and have a sense of purpose for starting their grind.

**Comment by M-I-G** [comment]
I think an achievement system is a really great idea. To my experience Tetrio users love to grind badges, they often post when they achieve the secret grade badge and many users started to learn PC-s just to get the PC badge, so i really think that similar challenges would be very much welcomed. 

In my opinion it would be nice to have a separate system for these rather than badges, since too many badges appearing on a profile would be distracting and would lower their value. Badges could be kept only for really special achievements.

Some ideas for challenges: 

1. Clear 10,100,1000,... amount of lines. 
2. Clear 10,100,1000,... amount of doubles, triples, quads.
3. 1,5,10,15,20 TSD in a sprint.
4. Do a 1,5,10,20,50,100,... long back-to-back chain.
5. Have 1,10,50,100,.. games/wins in tetra league.
6. Get top20, top10, 3rd, 2nd, 1st in quick play.
7. Get a rank, get >D, >D+,>C-,>C,.. rank (this way your all time highest rank would be acknowledged).
8. Get to lvl 1,10,20.. in zen mode.
9. Survive x seconds in zen mode with cheese timer on 4,3,2,1s with 100% messiness.
10. Have a sprint time below 200,150,130,120,110,100,...60,55,50,45,40,35,30,28,26,24,22,20,19,18.. seconds.
11. Achieve a blitz score over x.
12. Do a 3,4,5.. combo.
13. Clear 2,3,4? quads in a combo.
14. Clear 2,3,4? TSD in a combo.
15. Clear a TST, STSD, DT cannon, PC...
16. If maps are implemented, then clearing them could be achievements too.
17. Have a clean sweep, tiebreaker in tetra league.
18. Win a custom room game.
19. Beat a higher ranked or X ranked player in tetra league.
20. Win x rounds in quick play.
21. Doing formations other than secret grade.
22. Complete a sprint without using hold.
23. Win in quick play without using hold/quads/Tspins...

Probably there a lot more creative ideas people can come up with. 

Each achievement completed could reward the player by a certain amount of achievement points which would allow the possibility of a new leaderboard.
For challenges like "clear x amount of lines" the achievement points could be a function of x and x could go up to infinity similar to the lvl system. If you decide to implement this idea and want my help, then I could probably figure out a suitable function for these.

**Comment by mat1jaczyyy** [comment]
a

**Comment by dginovker** [comment]
I'd love this! As long as the achievements aren't overcrowding and appearing nonstop, this would be a great goal setter and side feature :)

**Comment by AndyThePie** [comment]
comment because i like this idea

**Comment by flashwave** [comment]
there u go

**Comment by ski3r3n** [comment]
well isnt this done

**Comment by ZaptorZap** [comment]
yup
