### ISSUE TITLE
Restrict Custom Rooms Based off Rating (40L Records, Tetra League Rating, etc.)

### ISSUE THREAD

**Issue by DanKruse731** [tetrio/issues#276]
### Conflict
In the Room Listings, I always find a room labelled "Noobs Only", "Beginners Only", etc., and when I enter those rooms, there's the chance that a player is superior to everyone in the room. A player with a record of sub40 could win consistently, and then the other players would be hindered by him/her.

### Solution
A good solution would be to restrict the players based off their rating, whether it's how fast they can clear 40 lines, or their Tetra League Rating. An option like this should likely be in conjunction with the "Allow Anonymous Users to Join" option.

**Examples**
- A "Beginners Only" room would be limited to those who have not reached a sprint record of 60 seconds. People with a record of under 60 seconds could still spectate, but not be able to play.
- A "Sub-30" room could be limited to those with a sprint record ranging from 20 to 30 seconds.
- A "B-Rank" room could be limited to players with a Tetra League grade ranging from B- to B+.

### Current Remedy
The only solution as of now would be for the host to kick the superior player, but seems a little unjustified.

**Comment by csq-curiosity** [comment]
This looks like a good idea, but we probably need more customization options so that arbitrary options is available. The reason being that, for example, a sprint record between 30 and 20 seconds is a difference of 3.33pps and 5pps. For most players, a difference of a fraction of a pps can determine the victory and defeat, and a range of 1.33pps is quite a lot.

**Comment by Dimentio** [comment]
Added in next update!
