### ISSUE TITLE
Unintentional double hard drop on DS4 d-pad

### ISSUE THREAD

**Issue by Greenjoepie** [tetrio/issues#306]
### Describe the bug/issue
During gameplay, occasionally when hard dropping the next piece instantly hard drops as well even though up on the d-pad is only pressed once, it happens often enough to where the game becomes slightly unplayable.
I'm not entirely sure if this is a bug or somehow my own fault but i've never run into this problem with other pc tetris games (e.g. puyo puyo tetris).

### Reproducing
1. Play any mode
2. Hard drop frequently

### Expected behavior
Only 1 hard drop every time i press up on the d-pad

### Your setup
 - **OS and version**: Windows 10 version 1909
 - **Browser and version**: Chrome 81.0.4044.129

### Additional (con)text
If this turns out not to be a bug, the option to reject hard drops for a certain amount of frames after another hard drop could fix the problem?

**Comment by csq-curiosity** [comment]
Related (and possibly a duplicate) to #305 

Dualshock 4 is known to cause this problem since DS4 has a connected d-pad, which often causes glitchy inputs if you're pressing left or right in a certain way.

If you haven't had this problem in Puyo Puyo Tetris, it is likely because the game has a 6 frame ARE; that is, there is a 6 frame (or 0.1 second) window where the piece doesn't spawn, and it's only after 6 frames has passed that the piece spawns, and therefore the game responds to your input. It is likely that your glitchy input happens within 6 frames, which is why you don't run into this in PPT but you do in tetrio.

Tetrio is meant for a fast paced gameplay, so adding a game-wide ARE would be an unpopular choice for many. Unless you want to play some custom games where you can set a certain amount of ARE, or change the controller, this is a problem that the devs cannot handle, because there really isn't anything inherently wrong in the game that causes this.

**Comment by LayneTheEpic** [comment]
You could make sure that you have 'prevent accidental hard drops' enabled and see if that helps
