### ISSUE TITLE
Input duplication after reconnecting controller over and over. 

### ISSUE THREAD

**Issue by reegly** [tetrio/issues#370]
### Describe the bug/issue
After reconnecting the controller for some reasons inputs a duplicating. At least in the menu navigation. Switching between menus becomes much faster. Restarting the game fix the issue.

### Reproducing
1. Connect the controller
2. Disconnect the controller
3. Connect it again

### Your setup
 - Windows 10
 - Desktop version
 - Tested on 8bitDo sn30 Pro+ and Nintendo Switch Pro controller

**Comment by Speedphoenix** [comment]
Bump, this issue is still here, using a PS4 DS4 controller.
See here for example: https://i.imgur.com/MMwXPr2.mp4
The first controller connected message is when I pressed a button on the controller for the first time, and subsequent ones from when I unplugged and plugged again the controller.

Another example where I pressed the *back* button once, after having reconnected many times: https://i.imgur.com/1WNKRFz.mp4

Tetr.io Desktop version 6.0.9
Windows 10 version 2004

**Comment by o5k** [comment]
Fixed in next version.
