### ISSUE TITLE
graphic bug

### ISSUE THREAD

**Issue by LoukasJuritsch** [tetrio/issues#376]
Hi Osk! I am just here to report a minor bug in the Tetr.io website. 
It is when after a quick play match, you still see the message at the top of the screen that notifies you who you are spectating (I hope that the image makes it clear).

To reproduce the bug, you have to:
1. Enter a quick play match
2. Lose the match
3. Be spectating someone at the end of the match
4. Exit the Rankings page and enter the Lobby
5. The Graphic telling you who you are spectating will remain present at the top of the screen.

The expected behavior is for the graphic to disappear after the match is over and you enter the rankings page.

Here is a screenshot of the bug in action
![Capture](https://user-images.githubusercontent.com/50422960/85188355-d0a9e600-b273-11ea-9dfb-deb60a49065e.JPG)

Here is my setup: I am using Windows ten and the most recent version of Google chrome as of me sending you this; my computer is a dell inspiron 15 from around 2015 with upgraded ram from 4 gb to 8 gb

In terms of additional context, my computer is generally very laggy on the tetr.io website and all other websites and applications. I can expect anywhere from 3 to 15 fps. I do not know if distance from the server may cause any problems as well. I am in southern Ontario, in Canada.

Also, I just want to say I'm a huge fan of the website. You did a Great job :D

**Comment by ZaptorZap** [comment]
Seems like this is caused by the "MINIMAL" graphics preset under the "VIDEO AND INTERFACE" category in the config. I had never experienced this issue until user "Fic✨#4370" brought it to my attention in [the official TETR.IO Discord server.](https://discord.gg/ufDb2XJ) When they mentioned their graphics preset as a possible cause [in their original report in the #issue-report channel,](https://discord.com/channels/673303546107658242/673305614318960671/789386013461184542) I suggested they try out "LOW" settings as I went and tested a "quick play" match with "MINIMAL GRAPHICS" enabled. 
![image](https://user-images.githubusercontent.com/64891705/102585675-b789d100-4100-11eb-85fa-8dc7a5263673.png)
(my personal screenshot taken from Firefox 83.0, with no game modifications active)
![image](https://user-images.githubusercontent.com/64891705/102585774-e1db8e80-4100-11eb-9635-6eaa4d863823.png)
(Fic✨#4370's account of the bug in action)
