### ISSUE TITLE
Main game canvas is not high-DPI aware

### ISSUE THREAD

**Issue by Tenchi2xh** [tetrio/issues#382]
On a high-dpi screen, the main game canvas renders at the non-native pixel resolution instead of a doubled one. Unzooming the browser to 50% will produce a sharp, high-dpi image:

**Default**

![image](https://user-images.githubusercontent.com/4116708/85320981-37bdd980-b4c4-11ea-99c3-95e3950e4855.png)

**Browser unzoomed to 50%**

![image](https://user-images.githubusercontent.com/4116708/85320994-3be9f700-b4c4-11ea-944d-79dfbda162ef.png)

However, keeping the game at 50% will produce very small menus and texts etc. so it's not a viable solution. Ideally, an option would be available in the config to doubling of the canvas' internal resolution

Full screenshots:

<details><summary>Default</summary>
<img src=https://user-images.githubusercontent.com/4116708/85320404-4a83de80-b4c3-11ea-9c93-8846ae053aa5.png />
</details>

<details><summary>Browser unzoomed to 50%</summary>
<img src=https://user-images.githubusercontent.com/4116708/85320452-5d96ae80-b4c3-11ea-86ea-e0086c855183.png />
</details>

**Comment by o5k** [comment]
What graphics setting is this at?

**Comment by Tenchi2xh** [comment]
Medium, but I see the same behvior with High and Ultra as well (tried both desktop and site)

**Comment by 1lann** [comment]
Setting the PixiJS renderer's `resolution` option to `window.devicePixelRatio` (rather than `0` when `video.lowres` is not true) seems to fix it for me.

before:
![image](https://user-images.githubusercontent.com/804919/85359210-7d7da080-b4ca-11ea-85fc-0ef5ef9abcc0.png)


after:
![image](https://user-images.githubusercontent.com/804919/85359153-5aeb8780-b4ca-11ea-824f-f92b883ec4b1.png)

**Comment by o5k** [comment]
Fixed in next patch.
