### ISSUE TITLE
Unclear Garbage Setting in Zen Mode Failing to Register All Clears

### ISSUE THREAD

**Issue by csq-curiosity** [tetrio/issues#403]
### Describe the bug/issue
If you perform an all clear in either backfire or unclear garbage settings, you are expected to get a 10 line (x multiplier you've set to) garbage for performing it. In backfire setting it works fine, but in unclear mode the all clear isn't registered.

### Reproducing
1. Go to Solo -> Zen mode.
2. Perform an all clear.
Result: For example, if you manage to perform an quad all clear in unclear 1x setting, you would expect to receive 14 lines of garbage. (4 for quad + 10 for all clear) What happens instead is that you only receive 4 lines because all clear detection fails. This seems to be resulting from the game calculating garbage first (?) before registering all clears.

### Screenshots
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/62501780/85941343-4f321200-b95d-11ea-8fb0-4fc85ab705c0.gif)

### Your setup
 - Windows 10
 - Chrome 83

### Additional context
~~I can't meme about "instant death after all clear" with this bug present. Please fix~~

**Comment by Volleo6144** [comment]
I have confirmed that, if you get an all clear with a single (and so the all clear bonus itself is the only source of garbage), it _does_ work properly (however, because it only sends 20 lines on 2x unclear, you might still be able to clutch it out if you switch the garbage mode back to "off").

Unfortunately, GitHub doesn't support mp4 files as attachments, and converting the 4MB file to a GIF made it over six times bigger (and thus over the 10MB limit), so, uh...

...well, at least I have https://volleo6144.net/v/allunclear. (And yes, I did forget to remove that ugly black bar on the right side. until after recording it.)

**Comment by csq-curiosity** [comment]
bumpy

**Comment by csq-curiosity** [comment]
The bug is still present.

**Comment by deedeeen** [comment]
yo, someone bans the stale label for this issue

**Comment by deedeeen** [comment]
yo, somebody ban the stale label for this issue

**Comment by Dimentio** [comment]
Looked into this, it's simply how the engine handle all clears as their own attack separately (always 10), since you sent 1 line as part of your combo you receive the line before the engine process the all-clear check technically making your board not empty anymore therefore not an all-clear. It's made this way so all-clears are never combined/synergized into a huge attack.

**Comment by ZaptorZap** [comment]
Specifically, this was mentioned on the official combo table as a small footnote on the bottom:
![image](https://user-images.githubusercontent.com/64891705/195673037-c6dfe695-bf97-4ff3-81e5-12cd6fcc6ab4.png)
This implies that the garbage of an all clear is spawned after the single line you send, creating a _faux-cheese_ like boardstate to downstack through before getting to the 10 rows of clean garbage of TETR.IO's change-on-attack garbage generation scheme.

**Comment by csq-curiosity** [comment]
Just a heads up to a nearly 4-year-old issue report, this bug was fixed sometime on late 2023.

**Comment by Dimentio** [comment]
Can confirm I remember fixing it!
