### ISSUE TITLE
Account Deletion Process

### ISSUE THREAD

**Issue by LMoca** [tetrio/issues#438]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
1.) I have recently deleted my Tetr.io account to try the new delete feature.
2.) I receive an email, stating if I was sure I wanted to delete my username account. I proceeded with the procedure (the deletion visuals are really cool!) & stated that my account & username has been deleted.
2.) I login with my deleted username & password on the Tetr.io desktop app.
3.) I get a message box that says, "This account has been deleted."

### Reproducing
1.) Simply deleting a username account.

### Expected behavior
I was hoping to create the username from scratch again. I was expecting the username to be completely deleted off of the database, yet Tetr.io knows that username has been deleted. I was not expecting that behavior as Tetr.io claims the account has been deleted, but it still knows it existed. It should not exist on Tetr.io's database at all until said username is created & registered again. Tetr.io still recognizes the deleted username as a unique deletionID is present on the deleted username.

### Your setup
 - **OS and version**: [Windows 10]
 - **Browser and version**: [Chrome 84.0.4147.89]

**Comment by return215** [comment]
This is probably by design. It is done possibly to prevent someone to steal
one's username after it has been deleted. The same happens on Instagram and
Facebook, I guess. You cannot reuse a username/email once it has been
deactivated/deleted.

Let's say someone with the username "TonyBlock" deleted his account. People
can't just barge in and use his name for themselves. If this happens,
people will be confused if TonyBlock is still the same person as it was.

**Comment by o5k** [comment]
This is indeed by design, but not so much to prevent account name reuse (if you change your name, the original name _does_ get freed up, unless staff changed the name for you in which case the previous name is automatically blocked).

The real reason the account name stays locked is to prevent smurfing (one deletes their old account and creates a new account to throw matches, then play winning games constantly). A very small amount of info on your account is kept for this purpose (username, time joined, League stats, connections to other accounts), making the name unavailable.

If you wish for the account to be destroyed 100% and the name freed, please send an email or DM - I can then check if the account is good for full deletion.

**Comment by LMoca** [comment]
Gotcha! That makes a lot of sense when designed like that. I haven't thought of the possibility of 'identity theft' someone may potentially pull, even in a game like this. Kudos to that!
