### ISSUE TITLE
Is it possible that you can add a custom blocks?

### ISSUE THREAD

**Issue by Gamers-Life** [tetrio/issues#451]
I want to make a tetris game but its a Hololive edition but I'm still a student, doesn't have any knowledge about coding.

**Comment by ZaptorZap** [comment]
This is a bit of a confusing improvement. Any chance you're asking about custom block*skins?* If so, there's an addon that'll let you do what you want to do. Please take a look at [this page.](https://gitlab.com/UniQMG/tetrio-plus/-/wikis/home) If not, I'd suggest you elaborate a bit farther on this idea as I sure as heck don't understand it.

**Comment by kitokofox** [comment]
I don't feel like an Issue ticket is the best way to tell others you want to make a Tetris game. I would recommend talking to osk about what they did if its's for education purposes.

Aside from that, yes you can make custom skins, no you cannot have custom pieces. I think the correct phrase would be "Add the ability to create custom pieces/Tetrominoes" in that case. Otherwise I'm at a loss at what you want.
