### ISSUE TITLE
The same gravity numbers function differently when using levelling

### ISSUE THREAD

**Issue by w-i-d-e** [tetrio/issues#467]
### Checklist (issue will be disregarded & closed if incomplete!)

- [✓] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [✓] I am using the **newest version** of TETR.IO.
- [✓] I know **how to reproduce the issue**.
- [✓] I am using a **supported browser** or the Desktop Client.
- [✓] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [✓] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When in a custom game, setting "base gravity" when using levels does not produce the same gravity as setting "gravity" when not using levels

### Reproducing
1. Go to Custom game in the solo menu
2. Turn off leveling and set "gravity" to 5
3. Play and see that it's super fast
4. Turn on leveling and set "Base Gravity" to 5
5. Play and see that it's super slow

### Expected behavior
I expected that using the number 5 in "Base Gravity" would produce 5G, but that doesn't happen.

### Screenshots
Video of the issue (https://youtu.be/edT2oAhZAas) It is a few minutes long, because I test all sorts of settings to try and fix it.

### Your setup
Lenovo Yoga 520 laptop running Windows 10, desktop client

### Additional context
I was just trying to make a fun singleplayer mode when I realized that I couldn't understand what the gravity was doing. It just doesn't seem to make sense in any way I can think of. So I'm struggling to get the gravity right and it would be easier if this was fixed.

**Comment by csq-curiosity** [comment]
Guideline games have a gravity, or more specifically "time spent per row in seconds" formula of
(0.8-((Level-1)*0.007))^(Level-1)
in gravity-sensitive modes such as marathon.

"Base gravity" and "gravity increase" values are parameters for this equation. So,
(B-((Level-1)*I))^(Level-1)
What you've really done here is not make the gravity 5G, but made the formula
(5-((Level-1)*0.007))^(Level-1)
This actually means that the more levels you get into, the more time each piece spends.

Try toying around with the graph below to have a better idea on how the formula works. Remember, the graph should approach 0 as the level (x value) goes up in order to enjoy faster speeds in later games.

https://www.desmos.com/calculator/9yqxmdrvrw

**Comment by w-i-d-e** [comment]
Okay thanks for the info, I'll close this issue in that case
