### ISSUE TITLE
Tetra League false KO

### ISSUE THREAD

**Issue by Ads20000** [tetrio/issues#517]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [ ] I know **how to reproduce the issue**.
 - I can't complete this but this needs to be filed somewhere, feel free to close it.
- [x] I am using a **supported browser** or the Desktop Client.
 - I assume latest Firefox (81.0.2) is supported
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
In Tetra League, sometimes in a match after a while in each game Tetr.io will tell me I KO'd my opponent and their board will fall away as if they were KO'd but the game will not end and I continue to receive damage and the game continues as normal until I lose (in this instance I lost 0-5). The next game will work until fake-KO'ing again.

### Reproducing
Not reliably reproducible unfortunately :(
1. Go to https://tetr.io/
2. Click on 'MULTIPLAYER'
3. Click on 'TETRA LEAGUE'
4. Click on 'ENTER MATCHMAKING'
5. Wait for game to start, observe the bug described above mid-way into games.

Note: I use Minimal graphics, this may help with reproducing? This was also in a FT5 game against S- player (I was A+/A) TheSaltyWarrior.

### Expected behavior
The games play without false KOs and I'm thus able to see my board throughout each game.

### Screenshots
Screenshots? [Screencast!](https://github.com/tetrio/issues/files/5397024/Tetrio.false.KO.bug.zip)

### Your setup
 - Ubuntu 20.04
 - Firefox 81.0.2

**Comment by aarondme** [comment]
**Checklist (issue will be disregarded & closed if incomplete!)**

- [x] I've checked both open and recently closed issues to ensure this issue is not already reported.
- [x] I am using the newest version of TETR.IO.
- [ ] I know how to reproduce the issue.
- [x] I am using a supported browser or the Desktop Client.
- [x] I am not using anything that modifies game code (e.g. TETR.IO+).
- [x] I am certain this is a bug, not a feature request.

**Describe the bug/issue**
From my perspective, the game is normal, until I stop receiving my opponent's lines. On their screen it appears I misdrop and KO, but on mine I am playing normally. When the KO happens on their screen, they cannot send me lines anymore, but I can still send them lines. This also happened earlier the same day in a private lobby, it was not only in tetra league.

**Reproducing**
Play any online game...
I have no idea why/how this happens

**Expected behavior**
Game plays normally, opponent can send lines throughout and views my pieces as they are.

**Screenshots**
Video: https://youtu.be/JKQzzQxMnuE 
This is a different game than the above, but the same bug occurs.

**Your Setup**
Windows 10
Firefox 81.0.2
