### ISSUE TITLE
為甚麼我的帳號會顯示是別人的小號

### ISSUE THREAD

**Issue by 901206** [tetrio/issues#542]
為甚麼我的帳號會顯示是別人的小號，然後還禁我號，麻煩出來解決

**Comment by o5k** [comment]
Please only write issue reports in English, because Google doesn't know the difference between an alt account and a trumpet

![](https://kagari.moe/:/takei_hiroe.png)

Either way, please **email me** or **check the Discord (https://discord.gg/ufDb2XJ)** for account issues. Inquiries about account issues are not answered here.
