### ISSUE TITLE
Desktop Application Source Code

### ISSUE THREAD

**Issue by sc2ad** [tetrio/issues#566]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
Not necessarily, although I imagine it would be much easier to solve future problems and track future issues with the desktop application.

### Describe the solution you'd like
I was hoping the Tetr.io _desktop_ source code could be made public. As this seems to be an Electron application, it certainly doesn't seem hard to reverse engineer, but it may make things easier if the desktop application had its own repository (potentially with its own set of issues as well) and would also be open to contributions.

As for why this may be useful, I have noticed an occasional memory leak with the desktop application that is common to several Electron-based applications (the steps to reproduce are currently unknown, though, but in general, if you leave it open for around a week or so, it seems to do a similar impact).

I would be interested in attempting to fix this, as well as add several new configuration options (one being new in the latest version of the desktop client: the ability to continue playing music and running in the background even when not the active window).

### Describe alternatives you've considered
I understand that this may or may not be possible and that you have probably already considered making the desktop application open source in the past. Perhaps there is security critical information, or other reasons why the application remains closed source. In those cases, I can't help but wonder _why_, but (as a fellow software developer) I understand that some things are best left hidden, so I can completely understand.

### Additional context
It would be great to have another repository to fork and PR too 😄 Hope you have a great day and thank you for all your hard work!

**Comment by yesmeck** [comment]
I'd like to contribute too.

**Comment by othello777** [comment]
I would definitely support the project if it was open source

**Comment by reesericci** [comment]
yes!!!

**Comment by EthanDevelops** [comment]
This doesn't seem like it would help much, as it seems that the desktop application simply loads the tetr.io website alongside  some Discord RPC features, not the actual website source.

**Comment by JacobKfromIRC** [comment]
Is the browser application source code available? It doesn't seem to be in this repository

**Comment by pauliesnug** [comment]
> Is the browser application source code available? It doesn't seem to be in this repository
No, there isn't any update on this issue. However, the code isn't obfuscated, so you can simply use inspect element inside the app, since all it does is load the tetr.io website via Electron, nothing special.

**Comment by JacobKfromIRC** [comment]
Looking at https://tetr.io/bootstrap.js , it seems like that is not source code, but with how short it is maybe that is the source form. https://tetr.io/js/tetrio.js looks like it's partially source, but there's also a lot of minified or obfuscted parts as well, though that may be copies of existing libraries that have public source code available elsewhere.

**Comment by pauliesnug** [comment]
> Looking at https://tetr.io/bootstrap.js , it seems like that is not source code, but with how short it is maybe that is the source form. https://tetr.io/js/tetrio.js looks like it's partially source, but there's also a lot of minified or obfuscted parts as well, though that may be copies of existing libraries that have public source code available elsewhere.

Yes, the actual code of the tetr.io website is closed source and obfuscated. However, the desktop/electron code isn't obfuscated and all it does is load bootstrap.js inside an Electron app. This issue is about the Electron app, not the game itself, which will most likely not be open sourced

**Comment by JacobKfromIRC** [comment]
Thank you. I realized the issue was about the desktop application but I thought it would be a good place to ask about the browser application because I didn't see an existing issue for it so I thought I was just missing something. But based on your last comment it sounds like the game itself is not open source, which is what I was trying to figure out.

Would you happen to know of any equivalent games that are open source? I normally use the LibreJS extension to block nonfree JavaScript but I'd like to be able to play a game like this with friends. Maybe I'll just add an exception in LibreJS, but it seems silly to have to do that for something as simple as Tetris; I would have expected to find popular free implementations relatively easily.

**Comment by ZaptorZap** [comment]
Yes, you are correct. The game itself is not open source and osk has no plans to open source it. ( #937 / #1159 ) An open source Desktop client would not aid in having a libre connection, since TETR.IO's serverside code is under much more secrecy.
When it comes to open source titles, I can think of a few, but they're dated downloadable clients, not websites…
* [NullpoMino](https://github.com/nullpomino/nullpomino) is a dated Java stacker with ridiculous granularity when it comes to customization. You may host your own server or connect to a community-hosted Hard Drop server and play with up to 8 players.
* [Techmino](https://github.com/26F-Studio/Techmino) focuses on variety in single player, but it features multiplayer in some capacity(I've never played it). The [client's code](https://github.com/26F-Studio/Techmino/blob/942a789b9e1a84b7b2c8cd3852956d7459fcf49e/parts/net.lua) is available, of course, but I believe serverside is still closed source. (the previous [TechminoOnline](https://github.com/26F-Studio/TechminoOnline) repository has been archived since 3 years ago)
* [Tetra Legends](https://github.com/doktorocelot/tetralegends) is by far the most comparable to TETR.IO, as it's a JavaScript webgame, but it features no online capabilities. It was developed by a current TETR.IO developer!
