### ISSUE TITLE
40 Lines bug

### ISSUE THREAD

**Issue by yop2yop** [tetrio/issues#614]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
Before you lost in 40 Lines (40L Solo) the keyboard is blocked so you can't use it to move the menu.

### Reproducing
1. Go to 'Solo > 40 Lines'
2. Play and lost the game
3. Try to restart the game or quit with keyboard.

### Expected behavior
I expect the keyboard works but i need to use the mouse to restart the game.

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Google Chrome Versión 88.0.4324.104 (Build oficial) (64 bits)

### Additional context

VM28:7675 tetr-io_728x90_9 unmounted, now 0 mounts
VM28:7675 tetr-io_728x90_1 mounted, now 1 mounts
VM28:7675 PixiJS 5.2.2 - WebGL 2
VM28:7675 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 -CPU: 8-coreMemory: ~8 GBConnection: 10 Mbps, 0ms RTT [4g]
VM28:7675 Renderer: ANGLE (Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
VM28:192 Ribbon 62b8b1472c6c0d0f opened
VM28:7675 tetr-io_728x90_1 unmounted, now 0 mounts
VM28:7675 tetr-io_728x90_2 mounted, now 1 mounts
VM28:7675 tetr-io_728x90_2 unmounted, now 0 mounts

I try in Tetr.io desktop too and have the same problem

**Comment by csq-curiosity** [comment]
I don't know how to replicate the issue because it works fine for me.

Just to be sure that I am on the same page as you are, are you sure that you are not using the menu keys to try to navigate the game over screen? Because the game over screen is technically part of the in-game menu, so you should be navigating with the retry/forfeit keys instead of menu confirm/back keys.

![keyboard question mark](https://user-images.githubusercontent.com/62501780/106531460-a4588680-6531-11eb-840d-34b4ddacb1a0.PNG)

**Comment by yop2yop** [comment]
it's true, it was my mistake
