### ISSUE TITLE
Hide account details from rich presence

### ISSUE THREAD

**Issue by TayIorRobinson** [tetrio/issues#715]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
It would be nice to have the account details hidden on the Rich Presence.

### Describe the solution you'd like
![image](https://user-images.githubusercontent.com/74316107/121783485-cb415c00-cba6-11eb-83e0-f37831267319.png)
![image](https://user-images.githubusercontent.com/74316107/121783516-f035cf00-cba6-11eb-9aa1-fc9c6434b185.png)

### Describe alternatives you've considered
Turning the entire rich presence off is a solution, however it's nice to show that you're playing.

**Comment by ZaptorZap** [comment]
It's worth mentioning you can already do this…just turn off the rich presence ingame, and then manually add TETR.IO as an activity as described in #488:
![image](https://user-images.githubusercontent.com/64891705/93003615-b52b4000-f52f-11ea-90f8-ff166140b33a.gif)
Doing this on my Linux desktop causes the following information to be shown:
![image](https://user-images.githubusercontent.com/64891705/173215177-b3e8463b-e62a-4fac-a970-4308fc5076c2.png)
Since I believe this is precisely what you're looking for, I'll go ahead and close this issue as completed, since this is evidently a pretty niche feature, but if you were hoping to still show your ingame status without showing your username, then please reply—I'll happily reopen this.

**Comment by TayIorRobinson** [comment]
Yes, preferably what i was looking for was just the ability to hide the
username. Thanks for your response though.
