### ISSUE TITLE
Retry prompt in replays

### ISSUE THREAD

**Issue by FishPyramid** [tetrio/issues#729]
### Checklist (issue will be disregarded & closed if incomplete!)

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I know **how to reproduce the issue**.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [X] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue

The prompt that says "Keep holding to retry" will show up in replays

### Reproducing
1. Play singleplayer
2. tap retry bind
3. finish and watch replay

### Expected behavior

it might not be a bug but I think it's weird that it shows up in replays

### Screenshots

replay https://tetr.io/#R:Sd9r1PdNt 

### Your setup
- Windows 10
- Chrome Version 91.0.4472.124

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by ZaptorZap** [comment]
Actually, you can break the game even more with [a sort of "XRC" type replay.](https://cdn.discordapp.com/attachments/673303546564968566/765856470511255562/the_restart_replay.ttr) (download it and drag it into TETR.IO from the file explorer)

It takes advantage of this bug by artificially extending this key event, then having the replay end. It creates a sort of "ghost board" which you can control by starting another game, be it multiplayer or solo. You can very easily soft lock the game while this ghost board exists, since, i assume, it'll try to exit to the nonexistent replay stats if the ghost board tops out. Refreshing with `F5` removes the ghost board and gets you out of any softlocks however.

Never felt that this was worth making an issue report about, since you sort of have to purposefully edit a preexisting replay file to achieve this effect. I also made [another version which abuses the forfeit key](https://cdn.discordapp.com/attachments/673303546564968566/765857637669011456/suicidal_replay.ttr); it's much less harmful to the client as the replay just forfeits itself and returns silently back to the results screen.

**Comment by FishPyramid** [comment]
> Actually, you can break the game even more with [a sort of "XRC" type replay.](https://cdn.discordapp.com/attachments/673303546564968566/765856470511255562/the_restart_replay.ttr) (download it and drag it into TETR.IO from the file explorer)
> 
> It takes advantage of this bug by artificially extending this key event, then having the replay end. It creates a sort of "ghost board" which you can control by starting another game, be it multiplayer or solo. You can very easily soft lock the game while this ghost board exists, since, i assume, it'll try to exit to the nonexistent replay stats if the ghost board tops out. Refreshing with `F5` removes the ghost board and gets you out of any softlocks however.
> 
> Never felt that this was worth making an issue report about, since you sort of have to purposefully edit a preexisting replay file to achieve this effect. I also made [another version which abuses the forfeit key](https://cdn.discordapp.com/attachments/673303546564968566/765857637669011456/suicidal_replay.ttr); it's much less harmful to the client as the replay just forfeits itself and returns silently back to the results screen.

These are cool! What is also interesting is that the playable game made by the first one uses your handling settings and not mine

**Comment by o5k** [comment]
Fixed in next version.
