### ISSUE TITLE
Ghost piece to match custom skin color and not the default

### ISSUE THREAD

**Issue by CosmanAgraz** [tetrio/issues#734]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [x] I am using the **newest version** of TETR.IO.
- [x] I am certain this is a **feature request**, not a bug.
- [x] I've **thought this feature through** properly.

-----

### Is your feature request related to a problem? Please describe.
If a custom skin is applied, the ghost piece maintains the guideline tetromino colors.

### Describe the solution you'd like
I would like the option to:
1. Customize the ghost piece colors
2. Automatically get the custom skin color and apply that to the ghost piece.

### Describe alternatives you've considered
See above.

### Additional context
I use tetromino colors to identify each individual tetromino.  I also come from playing a tetris clone which uses different colors than guideline.  Not being able to use the colors Im used to hinders my gameplay.

Thank you.

**Comment by ZaptorZap** [comment]
Since customization of the blockskin is currently impossible without [the TETR.IO PLUS modification](https://gitlab.com/UniQMG/tetrio-plus/), this feature request is far outside the scope of the main TETR.IO project. Please resubmit this feature request to [TETR.IO PLUS's issue section](https://gitlab.com/UniQMG/tetrio-plus/-/issues), or, contribute it to #359.
