### ISSUE TITLE
Innapropriate account names

### ISSUE THREAD

**Issue by lonelynerd** [tetrio/issues#816]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Playername : Luden (https://ch.tetr.io/u/luden)

I was extremely bored today and we decided with a few friends to find usernames on various platforms, and i was astonished on how many inapropriate names we could find.

Seriously, it might be anons or innactive accounts, but i genuinely think its not a great thing to have these kinds of names  on the platform... 

This is only a few exemples, i have many more saved and if needed, i can send them aswell ( see in the "Additionnal context" tab )

### Describe the solution you'd like

Put a "naughty word" list to deny the creation of said accounts, to make the job easier for moderators and for people (me) to not mass report accounts again (Sorry to all the moderators for this, on the behalf of yacktenebreux and ecchou we kinda got ahead of ourselves).

### Describe alternatives you've considered

Alternative, put a bot to autodetect and remove existing/new accounts with inappropriate names.

### Additional context

Proof : 
https://cdn.discordapp.com/attachments/883455175547830292/906341452068565084/profile.png
https://cdn.discordapp.com/attachments/883455175547830292/906341802934665296/profile.png
https://cdn.discordapp.com/attachments/883455175547830292/906342147513524244/profile.png
https://cdn.discordapp.com/attachments/879301462499414016/906340845844832256/unknown.png
https://cdn.discordapp.com/attachments/879301462499414016/906339154219114496/unknown.png

Thank you for reading this, i hope this gets at least seen or solved in the future.
PS : I found more, many many more, if more proof is needed I can send, contact me on Discord if needed Luden#9146.

**Comment by o5k** [comment]
Such a filter already exists; files that are profane must be accepted first. Old usernames that were created before this are not rechecked, but can be reported through our ingame reporting system **if they are abused,** **not on GitHub**. These accounts are generally inactive though, as if they weren't, we'd ban them.

**Comment by lonelynerd** [comment]
But, in that case, we can't mass report that kind of account because of the "flood" the mods will have to go through. What can we do ?

**Comment by ZudoB** [comment]
The simple solution is to only report accounts *if they are actively causing an problem* - in other words, they're logged in and playing the game.

If you can only find an inappropriately named account by trying different permutations of bad words, they're not exactly causing a problem - the reason they're not banned is because nobody ever encounters them by chance.

**Comment by ZaptorZap** [comment]
As for deploying a banwave on naughty usernames, I can assure you such a banwave would cause havoc on genuine accounts after I've actively reviewed what words the filter catches in QUICK PLAY chat near daily since the 28th of May. There's a very good reason this filter, in regards to ingame chat, not registration, is optional.
