### ISSUE TITLE
Discord Rich Presence not working

### ISSUE THREAD

**Issue by ajs256** [tetrio/issues#838]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11 21H2

### Browser and version

TETR.IO Desktop v8

### Describe the bug/issue

I don't see TETR.IO in Discord, despite the RPC setting being enabled. I have to manually add the app.

### Reproducing

1. Enable Rich Presence in settings
2. Go to Discord
3. Observe that it's not listed

### Expected behavior

I see TETR.IO appear on my profile.

### Console logs

I don't see any errors:
![image](https://user-images.githubusercontent.com/67526318/144696406-ac3414a3-3c89-4699-a882-ee25a42fad51.png)

### Additional context

In #488, it is stated that the game has to be added manually, however in #715, it appears that the game implements a custom rich presence, which should not need to be manually added.

**Comment by ZaptorZap** [comment]
I'm quick to notice the Windows 11 version discrepancy here. Since Windows 11 is very much a new OS, one that TETR.IO Desktop V8 actually predates and therefore does not officially support, I'm somewhat sure this is why things aren't working properly. While I can't comment much on the Discord side of things, I do remember laughing at how things are seemingly still treated as Windows 10 on my personal Windows 11 laptop:
![image](https://user-images.githubusercontent.com/64891705/144697174-88127522-349e-43c2-b276-428d78338f21.png)
(Discord's bottom-of-settings shows that this is running on a "Windows 10 64-bit" system)

**Comment by ajs256** [comment]
Seems to have fixed itself:
![image](https://user-images.githubusercontent.com/67526318/145700719-7d878917-32ce-44f1-a953-a5e0746e86b3.png)
