### ISSUE TITLE
The game does not properly fall back if textures don't load

### ISSUE THREAD

**Issue by zacharylohrman** [tetrio/issues#840]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 Pro 10.0.19041

### Browser and version

Chrome 96.0.4664.45

### Describe the bug/issue

If the game cannot load image texture files, (for example, the skin texture), the game fails continue the code execution. While this isn't 100% necessary, gracefully falling back upon the textures' failing to load might be a good consideration.

### Reproducing

Start a game without the skin file being present; you can reproduce this manually by forcibly blocking the file in Chrome dev tools.

### Expected behavior

If the game cannot load the image file for something, have an emergency fallback that does not cause the JavaScript to throw and stop execution. For example, if the skin does not load, continue to play the game but with flat colors. If the ghost fails to load, use a faded version of the piece or don't show anything at all. Additionally, the game may automatically send a report for debugging.

### Screenshots

<img width="557" alt="image showing the tetrio board without the proper skins and black active piece" src="https://user-images.githubusercontent.com/19556715/144980667-7a868913-1872-47c6-b041-eec8098bb8db.png">

### Console logs

![image](https://user-images.githubusercontent.com/19556715/144979643-d011248e-5fbb-4359-8e0f-eea435ba5f7f.png)

### Additional context

Truthfully, this shouldn't be an issue unless something catastrophic happened with the web server. However, as the game may transition to including many skins as indicated by #359, it is probably a good idea to have this set up (additionally trying the default skin first, then the emergency fallback) so the game does not hang just because the server failed to retrive a skin of another player, which isn't neccesary to continue code execution.

**Comment by ZaptorZap** [comment]
I've got a small update from osk a while back (01/17/2022 UTC)
> theres 2 different issues here
① active piece is rendered black while it should be lighter ver of piececolor
② piece flash isnt baked yet so it crashes

> (piece flash is baked dynamically to adapt for semitransparent skins)

So it turns out we were blindsided by our graphics options, since it seems the only people who bothered to double check on this issue were the ones with ULTRA graphics selected. This explains why I recall it not effecting other users, since it seems like everyone else is on a Chromebook with MINIMAL graphics nowadays....here's a video of what that would look like, by the way:

https://user-images.githubusercontent.com/64891705/152493817-369f9d0a-6ed3-4ca6-9156-0908726f6d98.mp4

So yeah, not entirely fixed but *not entirely broken*. This also works on LOW graphics, but it fails to render starting at MEDIUM and higher.(I legitimately thought piece flash was still limited to HIGH and higher. Guess the effect's gotten cheaper since, since you can't even use a slider to turn it off on these graphics options anymore. That's fine by me though)

**Comment by o5k** [comment]
Fixed in next patch.
