### ISSUE TITLE
Randomly silenced 

### ISSUE THREAD

**Issue by DuePatronousREAL** [tetrio/issues#851]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Chrome

### Browser and version

Chrome

### Describe the bug/issue

I was in a tetra league game, playing against someone, when randomly, I get a message saying that I was silenced for "abusive chat" when the chat had been empty. 
I don't know when I was saying abusive things, but it wasn't during a tetra league game. I don't know if I'm being hacked, or if something else is happening, if anyone could tell me, I would appreciate it, my User name is DuePatronous

### Expected behavior

I wasn't expecting to me silenced during a tetra league game lol.

**Comment by ZudoB** [comment]
Your IP address was silenced, because a user on your network violated the rules. This may or may not affect your ability to chat while using this network - regardless, silences such as this do not affect your account standing in any way.

Account issues such as this are not suitable for the bug tracker and should be directed to support@tetr.io in future.

**Comment by DuePatronousREAL** [comment]
Okay, I'll remember this for future bugs I might see/
