### ISSUE TITLE
Crash while playing

### ISSUE THREAD

**Issue by HectorTMOficial** [tetrio/issues#876]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Desktop Client version 6.1.5

### Describe the bug/issue

I start to play and randomly the game freezes out of nowhere, becoming irresponsibe and the unic solutión is to Alf+F4, I thought it may happen due to the fact of having two screens, its not the case; or even having the feature that changes your wallpaper once every X time, its not the case either. I have tried playing with those unnabled or just one screen, it crashes. 

It usually happens in a game.  

It just happens in the Desktop Versión.

### Reproducing

1. Start whatever mode game.
2. Play.
3. Randomly happens 

### Expected behavior

Not crashing while playing

### Console logs

![imagen](https://user-images.githubusercontent.com/98089605/150320145-93beb112-1d6d-4e6a-bfb0-e72c5aae784b.png)
![imagen](https://user-images.githubusercontent.com/98089605/150320187-48fbe461-4931-42ef-b4bb-c2a4e4f0fcfa.png)

### Additional context

CPU             Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
RAM 	   16,0 GB
System based in 64 bits, CPU based in x64
Windows     11 Home
Version	   21H2
Version SO  22000.434
Windows Feature Experience Pack: 1000.22000.434.0

**Comment by PnsDev** [comment]
I'm having the same issue on both the web and desktop version. (Tested on two computers running windows 11.)

My screen goes black for a second and then the game is frozen. Could it be a graphic driver issue?

**Comment by HectorTMOficial** [comment]
I recently tried playing in another computer, running Windows 10,
completely different, different grafic settings and setup, just one screen.
It still happens to me. In most sure what's causing it.

**Comment by PnsDev** [comment]
I just had a 2 hour session with no crashes. It seems to have resolved itself for me.

**Comment by HectorTMOficial** [comment]
Well in my case, I updated my Controller, through the app from Windows
store, and I have resolved the issue, if it appears to you let me know and
so I could help you. This issues happens in many games in a weird and
random way and in my case it was due to the controller.

**Comment by ZaptorZap** [comment]
Considering some similarities to [a recent issue](https://discord.com/channels/673303546107658242/673305614318960671/960208503463624784) in [the TETR.IO Discord](https://l.tetr.io/discord)'s #issue-report channel, I'd say it's pretty evident that [one of the issues](https://www.reddit.com/r/techsupport/comments/kj3277/desktop_window_manager_crashing_sporadically/) does indeed stem from drivers for the Xbox Series X controllers, as Hector reports. I'll be closing the issue now, since it was kind of a meld of different problems:
- Vague initial report with sparse details or theories.
- "seems to have resolved itself" without being self-closed for over 20 days
- Issue doesn't seem to be one TETR.IO creates, but osk did send the following messages in the aforementioned #issue-report conversation:
> hmm, looks like the controller does disconnect or smth.. ill have to look into it
> generally planning to rewrite controller handling
