### ISSUE TITLE
'Bootloop' when trying to access tetr.io

### ISSUE THREAD

**Issue by acidrums4** [tetrio/issues#881]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Gentoo Linux

### Browser and version

Falkon 3.1.0 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Falkon/3.1.0 Chrome/87.0.4280.144 Safari/537.36)

### Describe the bug/issue

Since like 3 weeks ago, can no longer access to tetr.io. It keeps auto-refreshing a page that says

```
Checking your browser before accessing tetr.io.
This process is automatic. Your browser will redirect to your requested content shortly.

Please allow up to 5 seconds…
```

After said 5 secs, it seems to auto-refresh, but the message keeps going on and on.

### Reproducing

1. Go to tetr.io

### Expected behavior

tetr.io loads successfully so one can play, as it used to.

### Screenshots

![Screenshot_20220125_162434](https://user-images.githubusercontent.com/513421/151062284-143459bd-bc84-40db-a298-cd8f7f72f652.png)

### Console logs

![Screenshot_20220125_162617](https://user-images.githubusercontent.com/513421/151062502-b4db3b70-e7fa-402e-bef8-4f3ac5d81b7a.png)

### Additional context

I know this is not a "supported browser", but I can guarantee this was not happening 2-3 weeks ago and nothing was done on my part (browser hasn't been updated, no firewall, no proxies, no adblock, nothing).

**Comment by deedeeen** [comment]
This is a problem with Cloudflare, hmm.

**Comment by ZaptorZap** [comment]
As _vaguely and quickly_ pointed out, this is directly related to osk's recent utilization of [Cloudflare's "I'm](https://blog.cloudflare.com/introducing-im-under-attack-mode/) [Under Attack" mode](https://support.cloudflare.com/hc/en-us/articles/200170076) brought about due to [recent DDoSes against the TETR.IO servers](https://twitter.com/tetriogame/status/1477429061945339904), as there has been [in the past](https://twitter.com/tetriogame/status/1381222174925676550). Historically, these measures usually were switched off relatively quickly, however right now, that hasn't been an option.

**These measures do not impact the majority of TETR.IO users**, as they use more widely popular browsers such as Chrome or Firefox. Unfortunately there isn't much osk can do in this situation(aside from disabling the measure of course, but that has its clear downsides assuming attacks are still active), as Cloudflare is the provider responsible for this issue, but there are a couple workarounds I can suggest for yourself:
* First off, just try reloading with the with the `CTRL+F5` shortcut. If your browser picked up some bad cookie it might be trying to submit that over and over as well. Try resetting your local storage to combat that.
* A good secondary, easy to try troubleshooting step would involve changing your DNS to mirror that of Cloudflare's public DNS. You'll be looking to change it to `1.1.1.1`. Please search the internet for more specific instructions on changing your DNS.
* If this doesn't work, [Falcon's support page regarding vague loading problems](https://help.falcon.io/hc/en-us/articles/360027409132-FAQ-Why-Is-Falcon-Not-Loading-) is very quick to throw in the hat and suggest [contacting _their_ developers](https://help.falcon.io/hc/en-us/articles/360027667631-Contacting-the-Falcon-Support-Team). Remember, this issue involves passing [Cloudflare's automated checks against suspicious internet traffic](https://support.cloudflare.com/hc/en-us/articles/200170076-Understanding-Cloudflare-Under-Attack-mode-advanced-DDOS-protection-), so that will be great context to include if you do decide to contact them.
* If that goes nowhere, Cloudflare itself has [a community-ran forum of its own](https://community.cloudflare.com/), although I wouldn't be super confident in finding answers here. A quick site-wide search for "falcon" reaps no compelling results.
* If you'd like to sidestep the issue occurring on Falcon to begin with, might I suggest [the standalone TETR.IO Desktop application](https://tetr.io/about/desktop/)? It has native Linux releases. I'm no Gentoo user (I personally have been using Debian since Christmas 2020, so I can attest to the desktop app working here with the `.deb` package) so I suppose I'd just recommend the independent `.tar`ball download. (just extract it and run a quick `chmod +x tetrio-desktop` for good measure)
* Last resort: just wait for I'm Under Attack mode to be disabled. I don't think osk intends to keep it on _infinitely_, but if you do end up sitting it out wanna make it clear I'm not issuing any warranty or official decree here. It'll go off when it goes off, and I certainly don't know when that'll happen.
