### ISSUE TITLE
Allow to limit to 30fps

### ISSUE THREAD

**Issue by ajs256** [tetrio/issues#893]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I would like to be able to limit TETR.IO to 30 fps.

### Describe the solution you'd like

The ability to have a lower setting in Desktop's fps limiter than 60 fps

### Describe alternatives you've considered

n/a

**Comment by ZaptorZap** [comment]
This is, honestly, an incredibly niche feature request that likely won't be implemented, since you can just change your computer's refresh rate directly if you don't want apps running above that refresh rate for whatever reason. To be clear, that _is_ what TETR.IO Desktop's settings are mirroring, your graphics card/monitor's refresh rate in several factors(1X, 2X, 4X, ∞), since that is all they **can** mirror. Here's a guide on how to obtain your cinematic framerate, at least on Windows 11 (same principle applies for Windows 10 though, just use your search bars and keep in mind this is always an "Advanced setting" since the defaults are **usually** sane)
![image](https://user-images.githubusercontent.com/64891705/161864982-4bd65c3e-3401-4a68-801c-13905fb10c25.png)
And yes, I'm aware lower refresh rates aren't available on my very particular setup, at least, not without going into the BIOS settings and demanding a lower refresh rate from there instead. This is because these screenshots were rendered from a standalone all-in-one laptop, so the refresh rate here is extremely controlled. With NVIDIA's control panel, I can set a custom **frame rate limit** like so(I refuse to believe there's no equal option for AMD cards):
![image](https://user-images.githubusercontent.com/64891705/161865539-a809d633-cfa3-4392-9648-0b824eb26d32.png)
On Linux, libraries like [libstrangle](https://gitlab.com/torkel104/libstrangle) exist for this purpose as well.
