### ISSUE TITLE
Lost game without dropping a piece

### ISSUE THREAD

**Issue by rajun274** [tetrio/issues#913]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Chrome OS Version 99.0.4844.57 (Official Build) (64-bit)

### Browser and version

Chrome OS Version 99.0.4844.57 (Official Build) (64-bit)

### Describe the bug/issue

Please watch Round 4 from the attached replay file. Go to the final 2 seconds of play and look at the BUSTAMOVE274 board. Slow the game down to 0.25x speed. Notice where I'm about to place the S piece, and that there is room for the next piece (the Z piece) to spawn, even though there's incoming garbage. Notice that the board does not have red flames, meaning I am not about to top out. After I harddrop the Z piece, you can see the S piece spawn, you can see it move one to the right, then one down, then move more to the right. As the piece moves to the right, I lose the game, even though I did not hard drop. In other words, the game thought I lost even though I don't believe I had yet at that moment.

[bug_replay (78).ttrm.txt](https://github.com/tetrio/issues/files/8366277/bug_replay.78.ttrm.txt)

### Reproducing

Unsure, although this was actually the 2nd time I observed this bug that day (yesterday).

### Expected behavior

You can only lose after dropping a piece.

### Console logs

Sorry, I unfortunately don't have this. I can try providing it if I notice the bug again.

**Comment by ZaptorZap** [comment]
You very much _did_ lose after dropping a piece, you lost after holding the **`Z` piece**. The `Z` piece was allowed to spawn as the board simply didn't prevent it from doing so, but your available pieces afterwards, the `T` piece in next, and the `I` piece in hold, would've ended the game, since there's no line clear available to lower the stack.
![image](https://user-images.githubusercontent.com/64891705/160492752-5f3905df-5405-4684-9c0e-2d93dcdf80ca.png)
The game ending move was a **hold**, which explains the confusion. Some games prevent holding if it would cause a top-out, but TETR.IO not having that capability isn't a bug. That'd be a feature request, since osk would have to specifically implement such logic. None-the-less, placing a piece here would've ended the game similarly, since the `T` piece couldn't spawn anyway.
![image](https://user-images.githubusercontent.com/64891705/160492393-7091fe3b-f049-43d2-a355-9b517ea95130.png)

**Comment by rajun274** [comment]
Ah I understand now. Thank you for the explanation!!
