### ISSUE TITLE
Unintended "faux grid" view when spectating a user after topping out

### ISSUE THREAD

**Issue by DuePatronous** [tetrio/issues#941]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Chrome 

### Browser and version

Chrome

### Describe the bug/issue

When spectating a super lobby quick play game, I was switching the person I was spectating, trying to find someone, and eventually it looked weird, all of the boards went to the right, it was around top 20 (It varied).

### Reproducing

1 - Go quick play
2 - Wait until top 30/20
3 - Spam right/left arrow
4 - possibly see

### Expected behavior

For it to go to the next player

### Screenshots

![Screenshot 2022-05-09 7 57 55 AM](https://user-images.githubusercontent.com/81276924/167416041-72c3932b-5df4-4d27-b2d4-c071abc886e2.png)

**Comment by ZaptorZap** [comment]
Are you using "MINIMAL" graphics? If that's the case, then this is intended behavior; it occurs when you're spectating a player who tops out while boards are positioned to the right of the active board. I'm sure this limitation could be overlooked since you're not actually playing, and therefore performance isn't the most important thing to maintain, but MINIMAL is truly, seriously an **all or nothing** measure regarding performance over visuals.

For context, I was able to reproduce the visuals shown in your screenshot without spamming the left and right arrow keys by simply spectating a user about to top out while using MINIMAL graphics.

**Comment by DuePatronous** [comment]
No, I don't use Minimal graphics, I use low graphics
