### ISSUE TITLE
Lots more keyboard shortcuts for easy menu navigation

### ISSUE THREAD

**Issue by rajun274** [tetrio/issues#964]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Having to use & move the mouse to navigate Tetrio menus is cumbersome. I'd be able to much more quickly use Tetrio if there were a lot more keyboard shortcuts.

### Describe the solution you'd like

List of actions I would like a keyboard shortcut for, with the key recommendaton:

1. "Back" button (on the Multiplayer menu, Solo menu, etc): ESC key 
1. "Exit" button when in a room: ESC key
1. After League match ends, go back to "Multiplayer" screen: ESC key
1. On the homepage / main menu, a shortcut for "Multiplayer" (M key) and "Solo" (S key).
    1. Maybe do for the others like "Config", even though likely used not as often?
1. On "Multiplayer" screen, for all the options: "Tetra League" (T key), "Quick Play" (Q key), etc.
    1. Same for "Solo" screen.
1. When in "Multiplayer" menu, bring cursor to "enter room id or url..." textbox: / key (forward slash key)
    1. Same keyboard shortcut used in Google Search & Google Maps
1. _Maybe there are others!_

Ideas for making the keyboard shorts discoverable:

1. For the suggestion of "T key" for "Tetra League", "Q key" for "Quick Play", etc., underline that letter in each menu item.
3. Maybe somewhere in the ABOUT page, add the menu item "Keyboard shortcuts", and list them all.

### Describe alternatives you've considered

None?

**Comment by ZaptorZap** [comment]
There already are plenty of menu bindings by default. The ones suggested here seem extremely cumbersome to acquire muscle memory for, although I would see the utility of point 6. in your suggestions. **Here's a list of already implemented menu binds**, found in the ingame "CONFIG":
![image](https://user-images.githubusercontent.com/64891705/174702287-9d62c946-88a6-489b-a94b-f4c09ecfa3df.png)
Aside from these I **really** don't see a big population of extreme TETR.IO power users, especially when you weigh in the potential this has to interfere with custom keybinds/alternative keyboard layouts. If you absolutely must, then please use the built-in menuing keybinds with a combination of your favorite macro program to automate menu movement. The default positions for when you activate the menu binds should stay consistent and sane. (There's a huge difference between macroing ingame and macroing in the menus—needless to say, I don't think you'll have a significant edge over others if you can open 40 LINES miliseconds quicker)

For example, to implement your suggestions, assuming default binds:
1. Press `ESC` twice (one to activate the menu binds, and one to actually exit)
2. Press `ESC` twice
3. Press `ESC` thrice (the exit button for TETRA LEAGUE leaves you at the matchmaking screen—such that you could instead press `ESC` twice and enter once to continue matchmaking immediately)
4. Press `S` once and then hit `Enter` |  Press `S` twice and then hit `Enter`
    1. Press `S` or `W` as needed and then hit `Enter`

I think you get the point from this point onwards. I'll be closing this since it's pretty much already implemented. As for discovery—again, it's all listed at the very top category in the CONFIG.

**Comment by rajun274** [comment]
Hello!! Thanks for the reply!

Ahh I see what has happened. I'm using a CUSTOM in CONFIG, and I had never set keybindings to the shortcuts you're referring to. I've just set them to what I found in GUIDELINES, and it's working! Thanks!!

(TBH, I personally would not have looked there for the keybindngs, as I would assume they're hardcoded for all players. How often do players do non-default bindings? Anyway, this is a low priority thought.)

I appreciate your help!

**Comment by ZaptorZap** [comment]
Actually, I do lol

Just imported my settings from NullpoMino, which has a very centralized menuing schema. (`Shift` is used in-place of `ESC`. I avoid using my gameplay keys entirely, which are WASD based.)
Also, here's another quick tip I wouldn't blame you for not knowing: when you finish a 40L, BLITZ, or SOLO CUSTOM game, you can instantly retry without clicking the retry button by pressing whatever's bound to the ingame retry action.

**Comment by rajun274** [comment]
Ah ta da haha hilarious that I'm talking to someone that does different keybindings :P

Last request is so low priority, please ingore. Upon website open, the "Join" button can be pressed by "Menus: Confirm" keybinding.

Thanks so much reading my FR and providing your wonderful responses!!

**Comment by ZaptorZap** [comment]
This oversight is actually **on purpose**. I can't find the conversation now, but osk once explained that the click was necessary to confirm interaction with the site and your browser, so sound can actually play. (remember how browsers of today are extremely resilient to autoplaying sources?)

You can bypass the login screen entirely with [TETR.IO Desktop](http://tetr.io/about/desktop), where osk actually has control over the sound APIs there. In fact, you could even add this application to a game launcher like Steam and never touch your mouse from bootup to playing.

**Comment by rajun274** [comment]
Thank you again!!

(I actually play tetrio on a Chromebook 😬 that's very locked down due to security reasons.)
