### ISSUE TITLE
The desktop client is lagging too much.

### ISSUE THREAD

**Issue by Solid0528** [tetrio/issues#969]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Chrome 103.0.5060.53

### Describe the bug/issue

When I play this on Chrome, I can get a full 60fps while playing. 
However, when I launch the desktop client even with the same settings I can only get 8 frame per second on the main menu. 
Both versions have no other mods(TETR.IO PLUS and etc) installed.

### Expected behavior

I expected to get 60fps also on the client, because on March the client worked normally and had 60fps while playing quickplay too.

**Comment by ZaptorZap** [comment]
Could you post a screenshot of what you see when you press `F8`, as well as some statistics about the hardware you're running TETR.IO Desktop on?

**Comment by Solid0528** [comment]
I'm currently playing on lg gram(laptop).
It has 16GB RAM, i5-1155g7 cpu without extra graphic cards. (Windows 11)
screenshot link: https://imgur.com/a/5VXLrYr

**Comment by ZaptorZap** [comment]
Does the frequency of these crashes correlate to any **specific action** ingame? That is to ask: are they reproducible, or random in nature? Also, can you send over your console logs **after** a crash? You were asked to provide these when you were initially creating the issue report:
> Press F12 and go to the Console tab, then copy or screenshot the logs. This helps us quickly identify the cause of the bug.

**Comment by Solid0528** [comment]
About the first question, this happens every time when I just enter the main screen. Even with just scrolling the mouse or moving the cursor causes the lag. 
The screenshot of the Console tab is right here: https://imgur.com/a/OAwVZEr

**Comment by ZaptorZap** [comment]
So the issue is definitely explained a bit more with these rare errors, although you'll have to expand them(with the little arrow pointing to the left) so we can get a tiny bit more context:
![image](https://user-images.githubusercontent.com/64891705/175800484-c080be40-9ac5-4f58-b9ae-0aa4fad933b0.png)
I know I'm asking for a lot, but this is pretty much already verified as a local hardware issue—since the larger community never experiences these sorts of crashes. It's _possible_ that updating your graphics drivers could eliminate all of these issues, but if that doesn't cut it, then we might need a copy of your "dxdiag" results. (You can open the dxdiag tool by pressing Windows+R and typing `dxdiag`—it'll run automatically from there, since this tool comes installed with every copy of Windows since Windows Vista)

**Comment by Solid0528** [comment]
Updating the graphic driver worked! Thanks for the support!
