### ISSUE TITLE
ARR has too little range

### ISSUE THREAD

**Issue by zhannu** [tetrio/issues#973]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Chrome

### Describe the bug/issue

I think that this is bad enough to be considered a bug-the ARR in the config menu at most goes up to 83ms, which is much, much too fast for me to play without accidentally triggering DAS. And the only way to prevent my piece moving too far is to set the DAS to be abysmally slow.

### Reproducing

1:Play the game, at all.

### Expected behavior

I expected there to be a better range of delay between moving your piece once and DAS.

### Additional context

I usually play on the official website for tetris and set most of my highscores there, so it's infuriating that i can't have the same degree of comfort between the two.

**Comment by ZaptorZap** [comment]
Closed due to inaction/presumed ineptitude regarding configuration of TETR.IO's handling. [Recent replays of yours](https://ch.tetr.io/s/league_userrecent_62b8e7a1dc58a0968fd5c471) show extremely abnormal ARR properties and a confusion of how to preserve or activate DAS to begin with. I'll leave you with these suggestions:
* **Lower your ARR**
* **Change your DAS to be _higher_**
Your **DAS** is too low, here, and DAS has a far more generous scale(1Frame-20Frames), further showing that DAS is expected to be a high value.
