### ISSUE TITLE
Can't open TETR.IO under Wayland

### ISSUE THREAD

**Issue by Heisfer** [tetrio/issues#977]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Arch Linux

### Browser and version

Latest TETR.IO Client 

### Describe the bug/issue

When I try to open TETR.IO client I get this error
which: no tetrio-desktop" in (./"/opt/TETR.IO)

### Reproducing

1) Use Wayland not xwayland
2) Download latest version from Website or https://aur.archlinux.org/packages/tetrio-desktop

IF used tar version.
1). Go to untar folder
2) ./tetrio-desktop run this command

IF used AUR version
just run tetrio-desktop in terminal

### Expected behavior

Launch the damn thing.

### Screenshots

![image](https://user-images.githubusercontent.com/28564678/178464772-3593028e-a399-4777-ab4f-1ad437802ce0.png)
![image](https://user-images.githubusercontent.com/28564678/178464835-09acc4ef-d9a0-458b-bf2c-b8a87a19dfe9.png)

**Comment by ZaptorZap** [comment]
This seems like a more fundamental issue here with your $PATH—have you tried opening `/opt/TETR.IO/tetrio-desktop` directly? Furthermore, I'd advise you to read #817 regarding other Wayland issues on Firefox.

**Comment by Heisfer** [comment]
> 
No.
AUR Package bin is in /usr/bin/tetrio-desktop
And Downloaded tar file is in Downloads

This is the content of /opt/TETR.IO folder
![image](https://user-images.githubusercontent.com/28564678/178547695-9b791952-30df-4a1c-92cb-0be6beb2c9b0.png)


As you can clearly see the path in error is syntax error

**Comment by szymonszl** [comment]
tetrio-desktop is a binary tho, it's not a script so there's no syntax to error, especially nothing that'd call `which`
are you sure it's not something wrong with your shell? what happens if you try to run tetrio from an app launcher (as in, your start menu knockoff) if your rice has one? doubleclicking `tetrio-desktop` from a file browser? have you tried using a different shell, preferably less riced? are you sure arch is the distro for you?

**Comment by Heisfer** [comment]
> tetrio-desktop is a binary tho, it's not a script so there's no syntax to error, especially nothing that'd call `which` are you sure it's not something wrong with your shell? what happens if you try to run tetrio from an app launcher (as in, your start menu knockoff) if your rice has one? doubleclicking `tetrio-desktop` from a file browser? have you tried using a different shell, preferably less riced? are you sure arch is the distro for you?

I did terminal because it didn't open at all from launcher
I have tested it with ZSH and result is  the same

I know the file is binary it's just that there might be a small mistake in binary
Fun fact: To get the same output type which  ./'"'/opt/TETR.IO/tetrio-desktop'"'


I just released it that the same message comes from xwayland too but launches unlike Wayland native

**Comment by szymonszl** [comment]
run `env | grep "^PATH="` and `set | grep "^PATH="` and post the results

**Comment by Heisfer** [comment]
> https://cdimage.ubuntu.com/kubuntu/releases/20.04.4/release/kubuntu-20.04.4-desktop-amd64.iso

ubuntu uses xwayland so it isn't much difference. IT WORKS FINE ON XWAYLAND. :)

> `env | grep "^PATH="`

PATH=/home/heisfer/.config/composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl``

> `set | grep "^PATH="`

`PATH=/home/heisfer/.config/composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`

**Comment by ZaptorZap** [comment]
Looks like /opt/ is missing from that output, but then again my own copy is located in `/usr/local/bin/tetrio-desktop`(although it's just a linked file to `/opt/TETR.IO/tetrio-desktop`). 
![image](https://user-images.githubusercontent.com/64891705/178666964-11730e54-cd45-4213-98de-16276fa3d78e.png)

This path is *also* missing from that output, but _then again_ I'm sure there's subfolder nuance I wouldn't understand with your system's configurations. Afterall, my own system, one running Debian bullseye, doesn't have a linked file in `/usr/bin/tetrio-desktop`. I suggest you try the same exercise out to debug further: `whereis tetrio-desktop`
![image](https://user-images.githubusercontent.com/64891705/178605144-5c0bab9b-2ae1-4859-a8c3-a51113c65961.png)

<hr>

> [No.](https://github.com/tetrio/issues/issues/977#issuecomment-1182004534)

So…will you just once? Does TETR.IO open and work then? If so, Wayland **isn't the issue here**(sorry, but you seem adamant that it's a Wayland issue—what utility does Wayland have modifying shell behavior? `xwayland` presumably is just handling this strange linked file/path behavior a bit better and less literally than `bash`/`zsh` directly). In fact, I'm willing to say the issue here lies in [the unofficial AUR release](https://aur.archlinux.org/packages/tetrio-desktop) third-party user [Denton-L](https://aur.archlinux.org/account/Denton-L) published, which discredits it from being a valid issue in the scope of this repository. It's pasted at the bottom of every page on the site itself: _AUR packages are user produced content. Any use of the provided files is at your own risk._

Since you're not using a genuine release of the TETR.IO Desktop client, we just can't help you. With the provided `tar`ball, it's _your responsibility_ to reliably open the executable—afterall, we don't help Windows users fix their Desktop shortcuts, do we?
