### ISSUE TITLE
"Back to back" bonus is not awarded for Mini-T-Spin Singles during 2 combos

### ISSUE THREAD

**Issue by PragmaticAntithesis** [tetrio/issues#979]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 103

### Describe the bug/issue

"Back to back" bonus is not awarded for Mini-T-Spin Singles during 2 combos. Instead, they deal 1 damage regardless of the quality of the previous line clear.

### Reproducing

1. Clear a single with the next two pieces being "I" and "T".
2. Clear a Quad with the I. This deals 5 damage.
3. Clear a B2B Mini-T-Spin Single with the T. This deals 1 damage, for a total of 6.

### Expected behavior

A regular Mini-T-Spin Single deals 1 damage in a 2 combo. The "back to back" bonus adds at least 1 extra line of damage to the line clear. This should cause the Mini-T-Spin to deal at least 1+1=2 damage, for 7 in total.

### Additional context

I have encountered this unexpected behaviour in TETRA LEAGUE, but nowhere else. More investigation may be needed to see if this issue shows up in the other modes.

**Comment by ZaptorZap** [comment]
> This should cause the Mini-T-Spin to deal at least 1+1=2 damage

I know this seems backwards, but it's actually documented on [the combo table osk released quite some time ago](https://tetris.wiki/File:TETR.IO_Combo-Table.png):
![image](https://user-images.githubusercontent.com/64891705/179363870-f6da87ec-63fe-4dc5-9e32-1897a316a705.png)
So it'd appear this was in some form intended—or at least known about. Whatever the case, this's a rare issue, and I doubt people lose rounds routinely because of one missing attack line.

**Comment by o5k** [comment]
This is because the formula swaps over from the logarithmic 001111.... to +25% multiplier. As intended

**Comment by deedeeen** [comment]
pending public formulas for attacks then
