### ISSUE TITLE
Mid-game ads make lagspikes during multiplayer

### ISSUE THREAD

**Issue by MkTr** [tetrio/issues#982]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

My computer is 7 years old, so I'm not sure how this impacts more modern computers: every time an animated ad loads, my computer lags for a few seconds. With adblock, and in the previous version of tetrio, I rarely experience mid-game lag on my device: tetrio runs at full FPS without any input delay at medium graphics settings, and multiplayer games run smoothly (I have ethernet). But in the latest update, whenever an ad loads during a game, the quick random freezes practically guarantee a misdrop during multiplayer games, so I'm forced to play extremely carefully when I think an ad is about to load - something that's difficult to focus on when I'm thinking about the rest of the game. I understand you need more revenue, but the easiest way to solve this issue is by turning on adblock, ironically defeating the purpose of adding ads.

### Describe the solution you'd like

Could ads only load once per game at the start, so lag spikes only happen during the countdown? This would decrease the amount of revenue from quickplay and low-level fights, where each game takes 3-6 minutes to complete, but it would have little to no impact on high-level games, where every game is between 30 seconds and 2 minutes, and solo challenges, where restarts are frequent. 

### Describe alternatives you've considered

If that's too much to ask, then could ads load every minute instead of every 30 seconds? I'd take any compromise at this point, an ad every 30 seconds makes the game extremely tedious.

**Comment by o5k** [comment]
These solutions devalue the ad space so much that there'd be no point to them. In adding ingame ads, I am trying to target specifically the large (and evergrowing) group of TETR **.IO** players that mostly see the game as a distraction during class, or otherwise have zero connection with the game. Making a game free to play, not just in the sense of "no purchase", but also "no effort" (in browser, no install needed), means a majority of your playerbase simply has no connection to you or the game (and is as such also not monetizable in any other method). As such, **the ingame ads only appear to those playing in browser**. It is expected that those who genuinely care about the game either play on Desktop, have Supporter, or have an adblocker. (This tends to line up with statistics.)

As such, to resolve the issue, simply **use TETR.IO Desktop, get Supporter, get an adblocker, or firewall api.adinplay.com.** If it sounds strange that a publisher would tell players to use adblock...remember that well, I still care about your experience! The people who this monetization strategy is targeting is not the same people who'd read this issue report.

(In fact, the update made it so adblock users no longer see the ugly empty boxes. I could fill them with "pls turn off adblock!! :(" but why would I? That's not the point)
